# Generated by Django 5.0.1 on 2024-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('0', 'Consumer'), ('1', 'Vendor'), ('2', 'Admin')], default='0', max_length=10),
        ),
    ]
